config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root "static_pages#home"
  get "about", to: "static_pages#about"

  get "users", to: "users#index"
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "/auth/:provider/callback" => "sessions#omniauth"
  get "auth/failure", to: redirect("/")

  get "tasks/approved", to: "users#approved_tasks"
  get "tasks/approved/show", to: "tasks#approved_show"
  get "search", to: "search#index"
  get "mytasks", to: "users#mytasks"

  get "notifications", to: "notifications#index"
  delete "notifications/:id", to: "notifications#destroy", as: :destroy_notification
  patch "notifications/:id/seen", to: "notifications#seen", as: :seen_notification

  resources :users, only: %i[edit update show destroy]
  resources :tasks do
    patch "acceptance", on: :member
    patch "status", on: :member
    patch "category", on: :member
    patch "document", on: :member
    patch "done", on: :member
    delete "attachments/:id/purge", on: :member, to: "attachments#purge", as: "purge_attachment"
    resources :subtasks do
      patch "complete", on: :member
      patch "document", on: :member
    end
  end
  resources :categories
end
# rubocop:enable Metrics/BlockLength

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  validates :employee_id, :name, :priority, presence: true
  has_many_attached :documents
  has_many :subtasks, dependent: :destroy
  enum status: { pending: "pending", in_progress: "in progress", completed: "completed" }
  enum priority: { high: 1, medium: 2, low: 3 }
  enum repeat: { onetime: "onetime", daily: "daily", weekly: "weekly", monthly: "monthly", quarterly: "quarterly",
                 halfyearly: "halfyearly", yearly: "yearly" }
  default_scope { order(created_at: :desc) }
  scope :my_tasks, -> { where(employee_id: Current.user.id) }
  scope :with_priority, ->(priority) { where("priority = ?", priority) }
  scope :condition, ->(prop, value) { where("#{prop} = ?", value) }
  scope :with_date, ->(value) { where("date = ?", value) }
  scope :with_repeatation, -> { where.not(repeat: "Onetime") }
  def self.task_specific_statuses(task)
    if task.done
      Task.statuses
    else
      Task.statuses.reject { |k, _v| k == "completed" }
    end
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :require_user_log_in!
  before_action :admin_user, only: %i[index acceptance destroy]
  before_action :set_task, except: %i[index new create search]
  before_action :task_edit_access, only: %i[edit update]
  before_action :correct_task_user, only: %i[show status category document done]
  before_action :only_hr, only: :approved_show
  def index
    @tasks = Task.includes(:user).all.paginate(page: params[:page])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Current.user.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        TaskMailer.with(user: Current.user, task: @task).task_assigned.deliver_later
        format.html { redirect_to root_path, notice: "New Task Added" }
      else
        format.html { render "new" }
      end
      format.js
    end
  end

  def show
    @subtasks = @task.subtasks.paginate(page: params[:page])
  end

  def approved_show
    @subtasks = @task.subtasks
    respond_to do |format|
      format.html

      format.pdf do
        pdf = ApprovedTaskPdf.new(@task)
        send_data(pdf.render, filename: "Task_#{@task.id}.pdf",
                              type: "application/pdf", disposition: "inline")
      end
    end
  end

  def edit; end

  def update
    if @task.update(task_update_params)
      redirect_back(fallback_location: root_path, flash: { notice: "Task successfully updated" })
    else
      render "edit"
    end
  end

  def status
    @task.update_attribute(:status, params[:status])
    redirect_back(fallback_location: root_path, flash: { notice: "Task status updated" })
  end

  def category
    @task.update_attribute(:category_id, params[:task][:category_id])
    redirect_back(fallback_location: root_path, flash: { notice: "Task Category changed" })
  end

  def document
    if @task.update(document_params)
      flash[:notice] = "File uploaded"
    else
      flash[:alert] = "Something went wrong"
    end
    redirect_back(fallback_location: root_path)
  end

  def acceptance
    @task.acceptance = params[:value]
    if @task.save
      if @task.acceptance == "Approved"
        redirect_to task_path, { notice: "Task approved" }
      else
        redirect_to task_path, { alert: "Task rejected" }
      end
    else
      render "show", { alert: "Something went wrong" }
    end
  end

  def done
    @task.update_attribute(:done, params[:Done])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @task.destroy
    redirect_back(fallback_location: root_path, flash: { alert: "Task deleted" })
  end

  private

  def set_task
    @task = Task.find_by(id: params[:id])
    redirect_to root_path, alert: "Task does not exist anymore" unless @task
  end

  def task_params
    list_params_allowed = %i[name date time priority repeat employee_id category_id]
    params.require(:task).permit(list_params_allowed)
  end

  def task_update_params
    params.require(:task).permit(:name, :category_id, :date, :time, :priority, :repeat, :employee_id)
  end

  def document_params
    params.require(:task).permit(documents: [])
  end
end

app/views/tasks/_created_task_row.html.erb
<tr>
  <td><%= task.name %></td>
  <td><%= category_name(task) %></td>
  <td><%= task.priority.humanize %></td>
  <td><%= task.date %></td>
  <td><%= User.find(task.employee_id).name %></td>
  <td><%= task.repeat.humanize if task.repeat %></td>
  <td class="compl-status table-info"><%= task.status.humanize %></td>
  <td class="accep-status table-info"><%= task.acceptance %></td>
  <td><%= link_to "Edit",edit_task_path(id: task.id), class: "btn btn-primary", role: "button" %>
    <%= link_to "Show",task_path(id: task.id), class: "btn btn-secondary", role: "button" %></td>
</tr>

app/views/tasks/_form.html.erb
<%= form_with(model: task, url: tasks_path, local: false) do |f| %>
  <div class="modal-body">
    <div id="errorArea"></div>
    <div class="form-group mb-3 required">
      <%= f.label :name,"Task Name" %>
      <%= f.text_field :name, class: "form-control", placeholder: "Task Name" %>
    </div>
    <div class="form-group mb-3">
      <%= f.label :category_id, "Category" %>
      <%= collection_select(:task, :category_id, Category.all, :id, :name, {:prompt => true, :multiple=>false })%>
    </div>
    <div class="form-group mb-3">
      <%= f.label :date, "Required On" %>
      <%= f.date_field :date, class: "form-control"%>
    </div>
    <div class="mb-3">
      <%= f.label :time %>
      <%= f.time_field :time %>
    </div>
    <div class="form-group mb-3 required">
      <%= f.label :priority %>
      <%= f.select :priority, options_for_select(humanize_enum(Task.priorities)),prompt: "Please select", class: "form-control", required: true %>
    </div>
    <div class="form-group mb-3 required">
      <%= f.label :employee_id, "Assigned To" %>
      <%= collection_select(:task, :employee_id, User.all, :id, :name, {:prompt => true, :multiple=>false })%>
    </div>
    <div class="form-group mb-3">
      <%= f.label :repeat, "Repeat Interval" %><br>
      <%= f.collection_radio_buttons :repeat, humanize_enum(Task.repeats), :second, :first do |b| %>
        <%= b.label { b.radio_button + " " + b.text } %>
      <% end %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit class:"btn btn-primary btn-lg" %>
    <button type="button" class="btn btn-secondary btn-lg close-modal" data-bs-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/tasks/_mytask_row.html.erb
<tr>
  <td><%= link_to task.name, task %></td>
  <td><%= task.date %></td>
  <td><%= task.status.humanize %></td>
  <td>
    <% if Current.user.admin? || Current.user == task.user %>
      <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          Actions</a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><%= link_to "Edit",edit_task_path(id: task.id), class:"dropdown-item"%></li>
          <li> <%= link_to "Show",task_path(id: task.id), class: "dropdown-item" %></li>
          <% if Current.user.admin? %>
            <li> <%= link_to "Delete",task_path(id: task.id), method: :delete,data: { confirm: "Are you sure?" }, class: "dropdown-item" %></li>
          <% end %>
        </ul>
      </div>
    <% else %>
      <%= link_to "Show",task, class:"btn btn-secondary"%>
    <% end %>
  </td>
  <td class="text-center">
    <%= check_box_tag 'Done', true , task.done,
          onchange: "$(this).data('params',  this.checked)",
          data: { remote: true, url: done_task_path(id: task.id), method: :patch }%>
  </td>
</tr>

app/views/tasks/approved_show.html.erb
<div class="col-lg-6 mx-auto table-responsive">
  <table class="table table-striped">
    <h2>Task Details</h2>
    <tr>
      <th> Task Name</th>
      <td><%= @task.name%></td>
    </tr>
    <tr>
      <th> Category</th>
      <td><%=category_name(@task)%></td>
    </tr>
    <tr>
      <th>Required On</th>
      <td><%= @task.date%></td>
    </tr>
    <tr>
      <th>Created By</th>
      <td><%= @task.user.name%></td>
    </tr>
    <tr>
      <th> Assigned to</th>
      <td><%= task_employee_name(@task) %></td>
    </tr>
    <tr>
      <th>Repeat Interval</th>
      <td><%= @task.repeat.humanize if @task.repeat%></td>
    </tr>
    <tr>
      <th>Completion Status</th>
      <td>
        <%= @task.status.humanize %>
      </td>
    </tr>
    <tr>
      <th>Acceptance Status</th>
      <td><%= @task.acceptance %></td>
    </tr>
    <tr>
      <th>Uploaded Document</th>
      <td>
        <% if @task.documents.attached? %>
          <% @task.documents.each do |document| %>
            <%= link_to document.filename , rails_blob_path(document, disposition: "inline"), target: "_blank", style:"margin-right: 10px"%>
          <% end %>
        <% else %>
          <h6>No Document</h6>
        <% end %>
      </td>
    </tr>
  </table>
  <div class="col-lg-2 mx-auto">
    <%= link_to "Print Pdf", tasks_approved_show_path(id: @task.id, format: "pdf"), target: "_blank", class:"btn btn-primary" %>
  </div>
  <%= link_to "Back", :back, class: "btn btn-outline-secondary" %>
</div>

app/views/tasks/create.js.erb
<% if @task.errors.any? %>
  $('#errorArea').html("<%= j render('shared/errors', object: @task)%>")
<% else %>
  $('#createdTasksTable').prepend("<%= j render('created_task_row', task: @task)%>")
  <% if @task.employee_id == Current.user.id %>
    var id = '#'+ <%= Task.priorities[@task.priority] %>
    $( id+' table tbody').prepend("<%= j render('mytask_row', task: @task)%>")
  <% end %>
  $('.close-modal').click()
<% end %>

app/views/tasks/edit.html.erb
<div class="col-lg-6 mx-auto mt-5">
  <h1>Edit Task</h1>
  <%= form_with model: @task, url: task_path do |f|%>
    <%= render 'shared/errors', object: @task %>
    <div class="mb-3 required">
      <%= f.label :name,"Task Name" %>
      <%= f.text_field :name, class: "form-control", placeholder: "Task Name", required: true %>
    </div>
    <div class="form-group mb-3">
      <%= f.label :category_id, "Category" %>
      <%= collection_select(:task, :category_id, Category.all, :id, :name, {:prompt => true,:include_blank =>"None", :multiple=>false, selected: @task.category_id })%>
    </div>
    <div class="mb-3">
      <%= f.label :date, "Required On" %>
      <%= f.date_field :date, class: "form-control"%>
    </div>
    <div class="mb-3">
      <%= f.label :time %>
      <% if @task.time %>
        <%= f.time_field :time, value: "#{@task.time.strftime("%H:%M")}"%>
      <% else %>
        <%= f.time_field :time %>
      <% end %>
    </div>
    <div class="mb-3 required">
      <%= f.label :priority %>
      <%= f.select :priority, options_for_select(humanize_enum(Task.priorities), selected: @task.priority), class: "form-control", required: true %>
    </div>
    <div class="mb-3 required">
      <%= f.label :employee_id, "Assigned To" %>
      <%= collection_select(:task, :employee_id, User.all, :id, :name, {:prompt => true, :multiple=>false })%>
    </div>
    <div class="mb-3">
      <%= f.label :repeat, "Repeat Interval" %><br>
      <%= f.collection_radio_buttons :repeat, humanize_enum(Task.repeats), :second, :first do |b| %>
        <%= b.label { b.radio_button + " " + b.text } %>
      <% end %>
    </div>
    <div class="mb-3">
      <%= f.submit "Update Task", class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= link_to "Back", :back, class: "btn btn-outline-secondary" %>
</div>

app/views/tasks/index.html.erb
<%= render partial:"shared/task_table" %>
<%= will_paginate @tasks, renderer: WillPaginate::ActionView::BootstrapLinkRenderer , previous_label: "Newer", 
next_label: "Older",inner_window: 1, outer_window: 0 %>
<%= link_to "Back", :back, class: "btn btn-outline-secondary" %>

app/views/tasks/new.html.erb
<div class="col-lg-6 mx-auto mt-5">
  <h1>Create New Task</h1>
  <%= form_with model: @task, url: tasks_path do |f|%>
    <%= render 'shared/errors', object: @task %>
    <div class="mb-3 required">
      <%= f.label :name,"Task Name" %>
      <%= f.text_field :name, class: "form-control", placeholder: "Task Name" , required: true %>
    </div>
    <div class="form-group mb-3">
      <%= f.label :category_id, "Category" %>
      <%= collection_select(:task, :category_id, Category.all, :id, :name, {:prompt => true, :multiple=>false })%>
    </div>
    <div class="mb-3">
      <%= f.label :date, "Required On" %>
      <%= f.date_field :date, class: "form-control"%>
    </div>
    <div class="mb-3">
      <%= f.label :time %>
      <%= f.time_field :time %>
    </div>
    <div class="mb-3 required">
      <%= f.label :priority %>
      <%= f.select :priority, options_for_select(humanize_enum(Task.priorities)),prompt: "Please select", class: "form-control", required: true %>
    </div>
    <div class="mb-3 required">
      <%= f.label :employee_id, "Assigned To", class: "required" %>
      <%= collection_select(:task, :employee_id, User.all, :id, :name, {:prompt => true, :multiple=>false }) %>
    </div>
    <div class="mb-3">
      <%= f.label :repeat, "Repeat Interval" %><br>
      <%= f.collection_radio_buttons :repeat, humanize_enum(Task.repeats), :second, :first do |b| %>
        <%= b.label { b.radio_button + " " + b.text } %>
      <% end %>
    </div>
    <div class="mb-3">
      <%= f.submit "Create Task", class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= link_to "Back", :back, class: "btn btn-outline-secondary" %>
</div>

app/views/tasks/new.js.erb
$("#newTaskForm").html("<%= escape_javascript render('form', task: @task) %>");

app/views/tasks/show.html.erb
<div class="row">
  <div class="col-md table-responsive">
    <table class="table table-striped">
      <h2>Task Details</h2>
      <tr>
        <th> Task Name</th>
        <td><%= @task.name%></td>
      </tr>
      <tr>
        <th> Category</th>
        <td><%=category_name(@task)%></td>
      </tr>
      <tr>
        <th>Required On</th>
        <% if @task.time %>
          <td><%= @task.date %> at <%= @task.time.strftime("%I:%M%p") %></td>
        <% else %>
          <td><%= check_nil(@task.date) %></td>
        <% end %>
      </tr>
      <tr>
        <th>Created By</th>
        <td><%= @task.user.name%></td>
      </tr>
      <tr>
        <th> Assigned to</th>
        <td><%=task_employee_name(@task)%></td>
      </tr>
      <tr>
        <th>Repeat Interval</th>
        <td><%= check_nil(@task.repeat).humanize %></td>
      </tr>
      <tr>
        <tr>
          <th>Done Status</th>
          <td> <%= 
            check_box_tag 'Done', true , @task.done,
            onchange: "$(this).data('params',  this.checked)",
            data: { remote: true, url: done_task_path(id: @task.id), method: :patch }%>
          </td>
        </tr>
        <th>Completion Status</th>
        <td>
          <%= select_tag( 'status', options_for_select(humanize_enum(Task.task_specific_statuses(@task)), { selected: @task.status } ), prompt: "Please select", data:{ remote: true, url: status_task_path(id: @task.id), method: :patch }) %>
        </td>
      </tr>
      <tr>
        <th>Acceptance Status</th>
        <td><b><%= @task.acceptance %></b></td>
      </tr>
      <tr>
        <th>Upload Document</th>
        <td>
          <%= form_with model: @task, url: document_task_url(id: @task.id) do |f|%>
            <div class="mb-3">
              <%= f.file_field :documents , accept: 'application/pdf, application/doc, application/xls', multiple: true, required: true%>
              <%= f.submit "Upload", class: "btn btn-primary" %>
            </div>
          <% end %>
        </td>
      </tr>
      <% if @task.status == "completed" && Current.user.admin? %>
        <tr>
          <th>Approve/Reject</th>
          <td>
            <div class="d-flex" style="gap:10px">
              <%= link_to "Approve", acceptance_task_path(value: "Approved"),method: :patch , class:"btn btn-success" %>
              <%= link_to "Reject",acceptance_task_path(value:"Rejected") , method: :patch , class:"btn btn-danger" %>
            </div>
          </td>
        </tr>
      <% end %>
    </table>
    <%= link_to 'Add Subtask', new_task_subtask_path(@task) , class: "btn btn-primary btn-lg mb-3", data:{ bs_target: "#newSubtaskModal", bs_toggle: "modal", remote: true}%>
  </div>
  <% if @task.documents.attached? %>
    <div class="col-md">
      <h2>Task Documents</h2>
      <div class="d-flex" style="gap:20px">
        <% @task.documents.includes([:blob]).each do |document| %>
          <div class="d-flex flex-column ", style="gap: 20px;">
            <%= link_to document.filename , rails_blob_path(document, disposition: "inline"), target: "_blank"%>
            <iframe src=<%= url_for(document) %> width="200" height="150"> </iframe>
            <div class="d-flex" , style="gap: 10px;">
              <%= link_to "Download" , rails_blob_path(document, disposition: "attachment"),class:"btn btn-primary", target: "_blank"%>
              <%= link_to 'Remove', purge_attachment_task_path(document),class:"btn btn-sm btn-danger",
                method: :delete,
                data: { confirm: "Are you sure?" } %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="row">
  <div class="col-md">
    <%= render 'subtasks/index'  %>
  </div>
  <div class="col-md my-4">
    <% @task.subtasks.each do |subtask| %>
      <% if subtask.documents.attached? %>
        <div class="col-md  my-1">
          <div class="d-flex">
            <b><%= subtask.title %> Documents: </b>
            <div class="d-flex">
              <% subtask.documents.includes([:blob]).each do |document| %>
                <div class="d-flex mx-2" style="gap: 10px">
                  <%= link_to document.filename , rails_blob_path(document, disposition: "inline"), target: "_blank"%>
                  <%= link_to ' <i class="fa fa-trash"></i>'.html_safe, purge_attachment_task_path(document), style: "color: red" ,
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<%= link_to 'Back', :back, class: "btn btn-outline-secondary" %>
<!-- New Subtask Modal -->
<div class="modal fade" id="newSubtaskModal" tabindex="-1" aria-labelledby="newSubtaskModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newSubtaskModalLabel">New Subtask</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="newSubtaskForm"></div>
    </div>
  </div>
</div>
<!-- Edit Subtask Modal -->
<div class="modal fade" id="editSubtaskModal" tabindex="-1" aria-labelledby="editSubtaskModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editSubtaskModalLabel">Edit Subtask</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="editSubtaskForm"></div>
    </div>
  </div>
</div>
<!-- Show Subtask Modal -->
<div class="modal fade" id="showSubtaskModal" tabindex="-1" aria-labelledby="showSubtaskModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="showSubtaskModalLabel">Subtask Details</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="showSubtaskForm"></div>
    </div>
  </div>
</div>