config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root "static_pages#home"
  get "about", to: "static_pages#about"

  get "users", to: "users#index"
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "/auth/:provider/callback" => "sessions#omniauth"
  get "auth/failure", to: redirect("/")

  get "tasks/approved", to: "users#approved_tasks"
  get "tasks/approved/show", to: "tasks#approved_show"
  get "search", to: "search#index"
  get "mytasks", to: "users#mytasks"

  get "notifications", to: "notifications#index"
  delete "notifications/:id", to: "notifications#destroy", as: :destroy_notification
  patch "notifications/:id/seen", to: "notifications#seen", as: :seen_notification

  resources :users, only: %i[edit update show destroy]
  resources :tasks do
    patch "acceptance", on: :member
    patch "status", on: :member
    patch "category", on: :member
    patch "document", on: :member
    patch "done", on: :member
    delete "attachments/:id/purge", on: :member, to: "attachments#purge", as: "purge_attachment"
    resources :subtasks do
      patch "complete", on: :member
      patch "document", on: :member
    end
  end
  resources :categories
end
# rubocop:enable Metrics/BlockLength

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :notifications, dependent: :destroy
  before_save { self.email = email.downcase }
  before_save { self.name = name.titleize }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX, message: "must be a valid email address" },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  enum role: { admin: "admin", hrd: "hrd", employee: "employee" }
  def admin?
    return true if role == "admin"

    false
  end

  def hr?
    return true if role == "hrd"

    false
  end

  # rubocop:disable Metrics/AbcSize
  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name.capitalize
      user.email = auth.info.email
      user.password = SecureRandom.hex
    end
  end
  # rubocop:enable Metrics/AbcSize
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_user_log_in!, except: %i[new create]
  before_action :admin_user, only: %i[index edit update destroy]
  before_action :only_hr, only: [:approved_tasks]
  before_action :set_user, only: %i[show edit update destroy]
  before_action :correct_user, only: :show
  before_action :check_no_task_assigned, only: :destroy
  def new
    if Current.user
      redirect_to root_path, notice: "Already logged in"
    else
      @user = User.new
    end
  end

  def index
    @users = User.all.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Successfully created account "
      redirect_to root_path
    else
      render "new"
    end
  end

  def show; end

  def edit; end

  def update
    if @user.update_attribute("role", user_update_params[:role])
      redirect_to users_path, { notice: "User successfuly updated" }
    else
      render "edit", { alert: "Try again!!" }
    end
  end

  def mytasks
    @my_tasks = Task.my_tasks
    @high_tasks = @my_tasks.with_priority(1).paginate(page: params[:page])
    @medium_tasks = @my_tasks.with_priority(2).paginate(page: params[:page])
    @low_tasks = @my_tasks.with_priority(3).paginate(page: params[:page])
  end

  def approved_tasks
    @approved_tasks = Task.condition("acceptance", "Approved").paginate(page: params[:page])
  end

  def destroy
    @user.destroy
    redirect_to users_path, { alert: "User deleted" }
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def user_update_params
    params.require(:user).permit(:name, :email, :role)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless Current.user.admin? || @user == Current.user
  end

  def check_no_task_assigned
    return if Task.condition("employee_id", params[:id]).empty?

    redirect_back(fallback_location: root_path,
                  alert: "You can only delete if there is no task assigned to the user")
  end
end

app/views/users/approved_tasks.html.erb
<div class="col-lg-6 mx-auto table-responsive">
  <table class="table all-task ">
    <thead class="table-primary">
      <tr>
        <th>Task Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% Array(@approved_tasks).each do |task| %>
        <tr>
          <td><%= link_to task.name, tasks_approved_show_path(id: task.id) %></td>
          <td>
            <%= link_to "Show",tasks_approved_show_path(id: task.id), class:"btn btn-secondary"%>
            <%= link_to "Print Pdf", tasks_approved_show_path(id: task.id, format: "pdf"), target: "_blank", class:"btn btn-primary" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @approved_tasks, renderer: WillPaginate::ActionView::BootstrapLinkRenderer , previous_label: "Newer", 
next_label: "Older",inner_window: 1, outer_window: 0 %>
  <%= link_to "Back", :back, class: "btn btn-outline-secondary" %>
</div>

app/views/users/edit.html.erb
<div class="col-lg-6 mx-auto">
  <h1>Edit User</h1>
  <%= form_with model: @user, url: user_path do |f|%>
    <%= render 'shared/errors', object: @user %>
    <div class="mb-3">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: "Your Name", disabled: true %>
    </div>
    <div class="mb-3">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", placeholder: "steve@apple.com", disabled: true %>
    </div>
    <div class="mb-3">
      <%= f.label :role %>
      <%= f.select :role, options_for_select(humanize_enum(User.roles), selected: @user.role), class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.submit "Update User", class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= link_to "Back", :back, class: "btn btn-outline-secondary" %>
</div>

app/views/users/index.html.erb
<div class="col-lg-6 mx-auto table-responsive">
  <table class="table table-striped">
    <h2 class="text-center">All Users</h2>
    <thead class="table-primary">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= user.email %></td>
          <td><%= user.role.humanize %></td>
          <td><%= link_to "Edit",edit_user_path(id: user.id), class: "btn btn-primary", role: "button" %>
            <%= link_to "Delete",user_path(id: user.id), method: :delete, data: { confirm: "Are you sure?" },  class: "btn btn-danger", role: "button" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, previous_label: "Previous", 
  next_label: "Next" ,inner_window: 1, outer_window: 0 %>
  <%= link_to "Back", :back, class: "btn btn-outline-secondary" %>
</div>

app/views/users/mytasks.html.erb
<h1 class="text-center">My Tasks</h1>
<div id="my_task" class=" row d-flex col-lg-12">
  <div class="col-lg-4" id="1">
    <h3 class="bg-danger">High Priority</h3>
    <%= render partial: "static_pages/priority_task_table" , locals:{tasks: @high_tasks}%>
  </div>
  <div class="col-lg-4" id="2">
    <h3 class="bg-warning">Medium Priority</h3>
    <%= render partial: "static_pages/priority_task_table" , locals:{tasks: @medium_tasks}%>
  </div>
  <div class="col-lg-4" id="3">
    <h3 class="bg-info">Low Priority</h3>
    <%= render partial: "static_pages/priority_task_table" , locals:{tasks: @low_tasks}%>
  </div>
</div>
<%= will_paginate @high_tasks, renderer: WillPaginate::ActionView::BootstrapLinkRenderer , previous_label: "Newer", 
next_label: "Older",inner_window: 1, outer_window: 0 %>
</div>
<%= link_to "Back", :back, class: "btn btn-outline-secondary" %>

app/views/users/new.html.erb
<div class="col-lg-6 mx-auto">
  <h1>Sign up</h1>
  <%= form_with model: @user, url: sign_up_path do |f|%>
    <%= render 'shared/errors', object: @user %>
    <div class="mb-3 required">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: "Your Name", required: true %>
    </div>
    <div class="mb-3 required">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", placeholder: "steve@apple.com", required: true %>
    </div>
    <div class="mb-3 required">
      <%= f.label :password %>
      <%= f.password_field :password , class: "form-control", placeholder: "password", required: true %>
    </div>
    <div class="mb-3 required">
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "password", required: true %>
    </div>
    <div class="mb-3">
      <%= f.submit "Sign up", class: "btn btn-primary" %>
    </div>
    <div class="mb-3">
      <%= link_to "Sign up with Google", "/auth/google_oauth2", class:"login-btn login-google", style:"text-decoration: none" %>
    </div>
    <div class="mb-3">
      <%= link_to "/auth/facebook" , class:"login-btn login-facebook" do %>
        <%= image_tag "facebook.png", style:"height:30px; padding-right: 10px; padding-left:0px;"%>Sign up with Facebook
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="profile">
  <div class="card">
  <i class="fa fa-user" style="font-size:72px"></i>
  <h1><%= @user.name %></h1>
  <p class="title"><%= @user.role.capitalize %></p>
  <p>Kreeti Technologies</p>
  <p><i class="fa fa-envelope"></i> <span><%= @user.email %></span>
  <p><button>Contact</button></p>
  </div>
</div>