config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root "static_pages#home"
  get "about", to: "static_pages#about"

  get "users", to: "users#index"
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "/auth/:provider/callback" => "sessions#omniauth"
  get "auth/failure", to: redirect("/")

  get "tasks/approved", to: "users#approved_tasks"
  get "tasks/approved/show", to: "tasks#approved_show"
  get "search", to: "search#index"
  get "mytasks", to: "users#mytasks"

  get "notifications", to: "notifications#index"
  delete "notifications/:id", to: "notifications#destroy", as: :destroy_notification
  patch "notifications/:id/seen", to: "notifications#seen", as: :seen_notification

  resources :users, only: %i[edit update show destroy]
  resources :tasks do
    patch "acceptance", on: :member
    patch "status", on: :member
    patch "category", on: :member
    patch "document", on: :member
    patch "done", on: :member
    delete "attachments/:id/purge", on: :member, to: "attachments#purge", as: "purge_attachment"
    resources :subtasks do
      patch "complete", on: :member
      patch "document", on: :member
    end
  end
  resources :categories
end
# rubocop:enable Metrics/BlockLength

app/views/shared/_created_task_table.html.erb
<div class="table-responsive">
  <table class="table">
    <thead class="table-dark">
      <tr>
        <th>Task Name</th>
        <th>Category</th>
        <th>Priority</th>
        <th>Required on</th>
        <th>Assigned To</th>
        <th>Repeat Interval</th>
        <th>Completion Status</th>
        <th>Acceptance Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody id="createdTasksTable">
      <% Array(@created_tasks).each do |task| %>
        <tr>
          <td><%= task.name %></td>
          <td><%= category_name(task) %></td>
          <td><%= task.priority.humanize %></td>
          <td><%= task.date %></td>
          <td><%= task_employee_name(task) %></td>
          <td><%= task.repeat.humanize if task.repeat %></td>
          <td class="compl-status"><%= task.status.humanize %></td>
          <td class="accep-status"><%= task.acceptance %></td>
          <td><%= link_to "Edit",edit_task_path(id: task.id), class: "btn btn-primary", role: "button" %>
            <%= link_to "Show",task_path(id: task.id), class: "btn btn-secondary", role: "button" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_display_notification.html.erb
<div class="dropdown drop_right">
  <a class="btn btn-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
    <i class="fa fa-bell"></i><span class="badge"><%= notifications.count %></span></a>
  <ul class="dropdown-menu p-3" aria-labelledby="dropdownMenuLink">
    <% if notifications.empty? %>
      <li> No unread notifications </li>
    <% end %>
    <% notifications.each do |notification|%>
      <div class="d-flex  align-items-center justify-content-around mb-3">
        <li style="width: 320px;"> <b><%= notification.desc %>  </b>
          <% if task_from_notification(notification) %>
            Follow the link to get the details:
            <b><%= link_to task_from_notification(notification), task_path(id: notification.task_id) %> </b>
          <% else %>
            <b>
              <p class="text-danger">Task has been deleted </p>
            </b>
          <% end %>
          <span class="m-3">
            <td><%= check_box_tag "seen", true , notification.seen, data: { remote: true, url: seen_notification_path(id: notification.id), method: :patch }%> </td>
            Mark as Read</span>
        </li>
        <div>
          <%= link_to ' <i class="fa fa-trash"></i>'.html_safe, destroy_notification_path(notification), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    <% end %>
    <li> <%= link_to "Show All", notifications_path %></li>
  </ul>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h6 class="text-danger"><%= pluralize(object.errors.count, "error") %> prohibited this object from being saved:</h6>
    <ul>
      <% object.errors.each do |error| %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <strong>
            <li><%= error.full_message %></li>
          </strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "TaskTracker", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        <% unless Current.user %>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link"%>
          </li>
        <% end %>
        <% if Current.user %>
          <% if ( Current.user.admin? ) %>
            <li class="nav-item">
              <%= link_to "All Users", users_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "All Tasks", tasks_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Categories", categories_path, class:"nav-link" %>
            </li>
          <% elsif Current.user.hr? %>
            <li class="nav-item">
              <%= link_to "Approved Tasks", tasks_approved_path, class:"nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "My Tasks", mytasks_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Create New Task", new_task_path, class: "nav-link"%>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 align-items-center">
        <% if Current.user %>
          <%= render "search/form" %>
          <%= render "shared/display_notification", notifications: @unread_notifications %>
          <li class="nav-item nav-link">
            <%= link_to Current.user.name, user_path(Current.user) %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, method: :delete,  class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", sign_up_path,class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path,class: "nav-link"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_task_table.html.erb
<div class="table-responsive">
  <table class="table all-task">
    <thead class="table-primary">
      <tr>
        <th>Task Name</th>
        <th>Category</th>
        <th>Created By</th>
        <th>Required on</th>
        <th>Assigned To</th>
        <th>Repeat Interval</th>
        <th>Acceptance Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% Array(@tasks).each do |task| %>
        <tr>
          <td><%= task.name %></td>
          <td>
            <div class="form-group mb-3">
              <%= collection_select(:task, :category_id, Category.all, :id, :name, {:prompt => true,:include_blank => "None", :multiple=>false, selected: task.category_id }, data:{ remote: true, url: category_task_path(id: task.id), method: :patch }) %>
            </div>
          </td>
          <td><%= task.user.name %></td>
          <td><%= task.date %></td>
          <td><%= task_employee_name(task) %></td>
          <td><%= task.repeat.humanize if task.repeat %></td>
          <td class="accep-status"><%= task.acceptance %></td>
          <td><%= link_to "Edit",edit_task_path(id: task.id), class: "btn btn-primary", role: "button" %>
            <%= link_to "Show",task_path(id: task.id), class: "btn btn-secondary", role: "button" %>
            <%= link_to "Delete",task_path(id: task.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger", role: "button" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>